### ISSUE TITLE
Make a gradle plugin for PIG

### ISSUE THREAD

**Issue by dlurton** [partiql/partiql-ir-generator#102]
The current process for using PIG with Gradle client projects involves either:

- [Configuring the client build to invoke the PIG command line](https://github.com/partiql/partiql-ir-generator/blob/afb1609d619ea8f5014c87617891ff8a3e1f84ad/pig-tests/build.gradle#L77)
- Adding a [dependency on PIG in  `$projectDir/buildSrc/build.gradle`](https://github.com/partiql/partiql-lang-kotlin/blob/main/buildSrc/build.gradle#L9) and then invoking PIG's [internal APIs to make it emit the generated code](https://github.com/partiql/partiql-lang-kotlin/blob/28701e23cf3bd397a67e8d9ab4f68feff953aea1/lang/build.gradle#L64-L89)
- Add a dependency on the runtime library.  [Example](https://github.com/partiql/partiql-lang-kotlin/blob/28701e23cf3bd397a67e8d9ab4f68feff953aea1/lang/build.gradle#L48)

While the latter is not a *terrible* experience per se, it is still far from optimal.  For instance:

- This method does not set Gradle up to run PIG only when the type universe file `.ion` has changed and instead runs PIG with every build.
- Adding a dependency on `generatePigDomains` to `compileKotlin` must be done manually.
- If there are multiple `.ion` files, each one must be added manually.
- The build output directory must be included manually as a source set or be placed under the main Kotlin source set.  

Whlie these things could be implemented by the client's `build.gradle` files, they are common enough tasks that I think it makes sense for us to publish a Gradle plugin that covers them and more.

This task will be to:

- [x] Create the plugin
- [x] Write documentation on its use in the root `README.md` file.
- [x] https://github.com/partiql/partiql-ir-generator/issues/132
- [x] Utilize the new plugin with the [Kotlin implementation of PartiQL](https://github.com/partiql/partiql-lang-kotlin).

**Comment by RCHowell** [comment]
https://plugins.gradle.org/plugin/org.partiql.pig.pig-gradle-plugin
