### ISSUE TITLE
Release request

### ISSUE THREAD

**Issue by dlurton** [partiql/partiql-ir-generator#112]
I'm working on some things that involve multiple permuted domains which generates large amounts of code.  Therefore, I really need #106.  Please release `main`.

**Comment by alancai98** [comment]
Sure, we can get the release started. Should be published to Maven by the end of the week.

**Comment by alancai98** [comment]
v0.5.0 w/ #106 is now released to Maven
- non-runtime: https://search.maven.org/artifact/org.partiql/partiql-ir-generator/0.5.0/jar
- runtime: https://search.maven.org/artifact/org.partiql/partiql-ir-generator-runtime/0.5.0/jar

Also created the v0.5.0 tagged release on GitHub: https://github.com/partiql/partiql-ir-generator/releases/tag/v0.5.0

Feel free to let us know if you have any issues with this release!
