### ISSUE TITLE
This library is incredible!

### ISSUE THREAD

**Issue by GavinRay97** [partiql/partiql-ir-generator#116]
I googled "Kotlin IR generate record class", and wound up here:

![image](https://user-images.githubusercontent.com/26604994/162518709-30c8dfbc-da76-47fb-973b-a739e3e0d72a.png)

Have a personal project where I've hand-written a query-expression AST/IR representation in Kotlin:

```kt
sealed interface Expression {

    sealed interface BinaryOperation : Expression {
        val left: Expression
        val right: Expression
    }

    sealed interface UnaryOperation : Expression {
        val operand: Expression
    }

    data class AND(override val left: Expression, override val right: Expression) : BinaryOperation
    data class OR(override val left: Expression, override val right: Expression) : BinaryOperation
    data class EQ(override val left: Expression, override val right: Expression) : BinaryOperation
	// ...
    data class NOT(override val operand: Expression) : UnaryOperation
    data class IS_NULL(override val operand: Expression) : UnaryOperation
    data class COLUMN(val name: String) : Expression
    data class LITERAL(val value: Any) : Expression
}
```

Looking at the code examples, this is essentially the exact same thing (data classes, visitors, etc) but probably more performant and maintainable.

Today was my lucky day I guess -- thanks for writing this, can't believe I've never heard of it and it only has ~~8~~ 9 stars!

**Comment by dlurton** [comment]
I just saw this for the first time today.  Thanks!

**Comment by dlurton** [comment]
It probably would have more stars if it had better documentation earlier on.  I didn't add the `README.md` file until a few months back.
