### ISSUE TITLE
Split generated code into multiple files

### ISSUE THREAD

**Issue by dlurton** [partiql/partiql-ir-generator#61]
With the project domain-to-domain feature transform I'm currently working on, generated `sample-universe.kt` file for the `sample-domain.ion` type universe is over 13k lines long and is getting a bit unwieldy.

We should instead generate one file per domain instead of putting all of the generated code into a one big file.

**Comment by dlurton** [comment]
I am picking this up today as I'm now now working with multiple permuted domains in the `partiql-lang-kotlin` repository up over 80k lines.  IntelliJ does *not* like Kotlin files this large at all: the IDE will stop recognizing symbols in files of this size, IntelliJ's editor shows references to valid symbols as red, even though the Kotlin compiler handles it just fine.

**Comment by RCHowell** [comment]
Checking in. Can we close this after #fdec2ef?
