### ISSUE TITLE
Migrate to Kotlin Latest Version of Kotlin

### ISSUE THREAD

**Issue by dlurton** [partiql/partiql-ir-generator#63]
The big feature we need here is the [explicit API mode for library authors](https://kotlinlang.org/docs/reference/whatsnew14.html#explicit-api-mode-for-library-authors), which makes missing visibility specifiers that are exposed to the public API either a warning or an error.  This is has been a big pain point for us since it is difficult to control the API surface area that we expose.

Enabling this feature will be a separate task.

**Comment by RCHowell** [comment]
Explicit library mode is in 1.4 which PIG is already on. Closing this, but keeping #64 open
